# Page d'accueil
UEOChoixBundle_homepage:
    pattern:  /
    defaults: { _controller: "UEOChoixBundle:Homepage:index" }


#Pages Etudiant
UEOChoixBundle_etudiant:
        resource: "@UEOChoixBundle/Resources/config/routing/etudiant.yml"
        prefix:   /etudiant

#Pages Admin
UEOChoixBundle_specialite:
        resource: "@UEOChoixBundle/Resources/config/routing/specialite.yml"
        prefix:   /specialite
UEOChoixBundle_module:
        resource: "@UEOChoixBundle/Resources/config/routing/module.yml"
        prefix:   /module
UEOChoixBundle_parcours:
        resource: "@UEOChoixBundle/Resources/config/routing/parcours.yml"
        prefix:   /parcours
UEOChoixBundle_moduleparcours:
        resource: "@UEOChoixBundle/Resources/config/routing/moduleparcours.yml"
        prefix:   /maquette

#Pages Utilisateur
UEOChoixBundle_utilisateur:
        resource: "@UEOChoixBundle/Resources/config/routing/utilisateur.yml"