UEO\ChoixBundle\Entity\Module:
    type: entity
    table: null
    repositoryClass: UEO\ChoixBundle\Entity\ModuleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        intitule:
            type: string
        semestre:
            type: smallint
            nullable: TRUE
        contenu:
            type: string
            nullable: TRUE
        nbInscrits:
            type: smallint
            nullable: TRUE
        nbPlaces:
            type: smallint
            nullable: TRUE
        professeur1:
            type: string
            nullable: TRUE
    lifecycleCallbacks: {  }
