<?php

namespace UEO\ChoixBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParcoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcoursRepository extends EntityRepository
{
}
