<?php

namespace Proxies\__CG__\UEO\ChoixBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Module extends \UEO\ChoixBundle\Entity\Module implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'intitule', 'semestre', 'contenu', 'nbInscrits', 'nbPlaces', 'professeur1', 'professeur2', 'professeur3', 'professeur4', 'professeur5', 'professeur6', 'professeur7', 'professeur8', 'professeur9', 'professeur10');
        }

        return array('__isInitialized__', 'id', 'intitule', 'semestre', 'contenu', 'nbInscrits', 'nbPlaces', 'professeur1', 'professeur2', 'professeur3', 'professeur4', 'professeur5', 'professeur6', 'professeur7', 'professeur8', 'professeur9', 'professeur10');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Module $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntitule($intitule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntitule', array($intitule));

        return parent::setIntitule($intitule);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntitule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntitule', array());

        return parent::getIntitule();
    }

    /**
     * {@inheritDoc}
     */
    public function setSemestre($semestre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSemestre', array($semestre));

        return parent::setSemestre($semestre);
    }

    /**
     * {@inheritDoc}
     */
    public function getSemestre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSemestre', array());

        return parent::getSemestre();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenu($contenu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenu', array($contenu));

        return parent::setContenu($contenu);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenu', array());

        return parent::getContenu();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbInscrits($nbInscrits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbInscrits', array($nbInscrits));

        return parent::setNbInscrits($nbInscrits);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbInscrits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbInscrits', array());

        return parent::getNbInscrits();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbPlaces($nbPlaces)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbPlaces', array($nbPlaces));

        return parent::setNbPlaces($nbPlaces);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbPlaces()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbPlaces', array());

        return parent::getNbPlaces();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfesseur1($professeur1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfesseur1', array($professeur1));

        return parent::setProfesseur1($professeur1);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfesseur1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfesseur1', array());

        return parent::getProfesseur1();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfesseur2($professeur2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfesseur2', array($professeur2));

        return parent::setProfesseur2($professeur2);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfesseur2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfesseur2', array());

        return parent::getProfesseur2();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfesseur3($professeur3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfesseur3', array($professeur3));

        return parent::setProfesseur3($professeur3);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfesseur3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfesseur3', array());

        return parent::getProfesseur3();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfesseur4($professeur4)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfesseur4', array($professeur4));

        return parent::setProfesseur4($professeur4);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfesseur4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfesseur4', array());

        return parent::getProfesseur4();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfesseur5($professeur5)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfesseur5', array($professeur5));

        return parent::setProfesseur5($professeur5);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfesseur5()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfesseur5', array());

        return parent::getProfesseur5();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfesseur6($professeur6)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfesseur6', array($professeur6));

        return parent::setProfesseur6($professeur6);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfesseur6()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfesseur6', array());

        return parent::getProfesseur6();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfesseur7($professeur7)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfesseur7', array($professeur7));

        return parent::setProfesseur7($professeur7);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfesseur7()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfesseur7', array());

        return parent::getProfesseur7();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfesseur8($professeur8)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfesseur8', array($professeur8));

        return parent::setProfesseur8($professeur8);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfesseur8()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfesseur8', array());

        return parent::getProfesseur8();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfesseur9($professeur9)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfesseur9', array($professeur9));

        return parent::setProfesseur9($professeur9);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfesseur9()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfesseur9', array());

        return parent::getProfesseur9();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfesseur10($professeur10)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfesseur10', array($professeur10));

        return parent::setProfesseur10($professeur10);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfesseur10()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfesseur10', array());

        return parent::getProfesseur10();
    }

}
