<?php

namespace Proxies\__CG__\UEO\ChoixBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Parcours extends \UEO\ChoixBundle\Entity\Parcours implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'intitule', 'nbOptions', 'dateDebutChoixS1', 'dateFinChoixS1', 'dateDebutChoix2', 'dateFinChoixS2', 'intituleCourt', 'anneeFormation', 'specialite_parcours', 'specialite', 'emailResponsable');
        }

        return array('__isInitialized__', 'id', 'intitule', 'nbOptions', 'dateDebutChoixS1', 'dateFinChoixS1', 'dateDebutChoix2', 'dateFinChoixS2', 'intituleCourt', 'anneeFormation', 'specialite_parcours', 'specialite', 'emailResponsable');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Parcours $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntitule($intitule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntitule', array($intitule));

        return parent::setIntitule($intitule);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntitule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntitule', array());

        return parent::getIntitule();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbOptions($nbOptions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbOptions', array($nbOptions));

        return parent::setNbOptions($nbOptions);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbOptions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbOptions', array());

        return parent::getNbOptions();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebutChoixS1($dateDebutChoixS1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebutChoixS1', array($dateDebutChoixS1));

        return parent::setDateDebutChoixS1($dateDebutChoixS1);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebutChoixS1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebutChoixS1', array());

        return parent::getDateDebutChoixS1();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFinChoixS1($dateFinChoixS1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFinChoixS1', array($dateFinChoixS1));

        return parent::setDateFinChoixS1($dateFinChoixS1);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFinChoixS1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFinChoixS1', array());

        return parent::getDateFinChoixS1();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebutChoix2($dateDebutChoix2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebutChoix2', array($dateDebutChoix2));

        return parent::setDateDebutChoix2($dateDebutChoix2);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebutChoix2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebutChoix2', array());

        return parent::getDateDebutChoix2();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFinChoixS2($dateFinChoixS2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFinChoixS2', array($dateFinChoixS2));

        return parent::setDateFinChoixS2($dateFinChoixS2);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFinChoixS2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFinChoixS2', array());

        return parent::getDateFinChoixS2();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntituleCourt($intituleCourt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntituleCourt', array($intituleCourt));

        return parent::setIntituleCourt($intituleCourt);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntituleCourt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntituleCourt', array());

        return parent::getIntituleCourt();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnneeFormation($anneeFormation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnneeFormation', array($anneeFormation));

        return parent::setAnneeFormation($anneeFormation);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnneeFormation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnneeFormation', array());

        return parent::getAnneeFormation();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpecialiteParcours(\UEO\ChoixBundle\Entity\Specialite $specialiteParcours = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpecialiteParcours', array($specialiteParcours));

        return parent::setSpecialiteParcours($specialiteParcours);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpecialiteParcours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpecialiteParcours', array());

        return parent::getSpecialiteParcours();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpecialite(\UEO\ChoixBundle\Entity\Specialite $specialite = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpecialite', array($specialite));

        return parent::setSpecialite($specialite);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpecialite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpecialite', array());

        return parent::getSpecialite();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailResponsable($emailResponsable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailResponsable', array($emailResponsable));

        return parent::setEmailResponsable($emailResponsable);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailResponsable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailResponsable', array());

        return parent::getEmailResponsable();
    }

}
